
module.exports = {
  content: [
    "./src/**/*.{js,jsx,ts,tsx}",
    "./public/index.html"
  ],
  theme: {
    extend: {
      colors: {
        'primary': '#ff69b4',
        'primary-light': '#ffb6d9',
        'primary-dark': '#ff1493',
        'secondary': '#ffc0cb',
        'accent': '#ff91a4',
        'pink-soft': '#ffe4e9',
        'pink-pastel': '#ffd6e0',
        'pink-50': '#fdf2f8',
        'pink-100': '#fce7f3',
        'pink-200': '#fbcfe8',
        'pink-300': '#f9a8d4',
        'pink-400': '#f472b6',
        'pink-500': '#ec4899',
        'pink-600': '#db2777',
        'rose-50': '#fff1f2',
        'rose-100': '#ffe4e6',
        'rose-200': '#fecdd3',
        'rose-300': '#fda4af',
        'rose-400': '#fb7185',
        'rose-500': '#f43f5e',
        'rose-600': '#e11d48',
        'white-cream': '#fff8f8',
        'white-ivory': '#fffff0',
        'white-snow': '#fffafa',
        'white-floral': '#fffaf0',
        'white-pure': '#ffffff',
        'white-pearl': '#fefefe',
        'white-lace': '#fefefe',
      },
      fontFamily: {
        'serif': ['Cormorant Garamond', 'serif'],
        'sans': ['Quicksand', 'sans-serif'],
        'mono': ['Share Tech Mono', 'monospace'],
        'cute': ['Comic Sans MS', 'cursive'],
        'handwriting': ['Kalam', 'cursive'],
      },
      animation: {
        'float': 'flutuar 3s ease-in-out infinite',
        'pulse-neon': 'pulse 2s infinite',
        'glow': 'textGlow 2s ease-in-out infinite',
        'glitch-skew': 'glitch-skew 1s infinite linear alternate-reverse',
        'glitch': 'glitch 500ms infinite',
        'blink': 'blink linear infinite 2s',
        'borderRadiusAnimation': 'borderRadiusAnimation 10s ease-in-out infinite',
        'imageFloat': 'imageFloat 6s ease-in-out infinite',
        'borderRotate': 'borderRotate 8s linear infinite',
        'borderPulse': 'borderPulse 4s ease-in-out infinite',
        'gridMove': 'gridMove 20s linear infinite',
        'borderGlow': 'borderGlow 3s linear infinite',
        'sparkleFloat': 'sparkleFloat 3s ease-in-out infinite',
        'techLineMove': 'techLineMove 3s ease-in-out infinite',
        'digitalPulse': 'digitalPulse 3s ease-in-out infinite',
        'glitchTop': 'glitchTop 3s infinite linear alternate-reverse',
        'glitchBottom': 'glitchBottom 3s infinite linear alternate-reverse',
        'cornerPulse': 'cornerPulse 2s ease-in-out infinite',
        'border-animate': 'border-animate 5s ease-in-out infinite',
        'pulseContact': 'pulseContact 0.5s cubic-bezier(0.5, 0, 0.5, 1) infinite alternate',
        'imageFade': 'imageFade 1s ease-in-out',
        'infoFade': 'infoFade 1s ease-in-out',
        'pulseProject': 'pulseProject 0.5s infinite alternate',
        'bounce-cute': 'bounceCute 1s ease-in-out infinite',
        'wiggle': 'wiggle 0.5s ease-in-out infinite',
        'float-cat': 'floatCat 3s ease-in-out infinite',
        'heart-beat': 'heartBeat 1.5s ease-in-out infinite',
        'sparkle': 'sparkle 2s ease-in-out infinite',
        'gradient': 'gradient 3s ease infinite',
      },
      keyframes: {
        flutuar: {
          '0%, 100%': { transform: 'translateY(0)' },
          '50%': { transform: 'translateY(-50px)' },
        },
        'glitch-skew': {
          '0%, 100%': { transform: 'skew(0deg)' },
          '10%': { transform: 'skew(2deg)' },
          '20%': { transform: 'skew(-3deg)' },
          '30%': { transform: 'skew(1deg)' },
          '40%': { transform: 'skew(-2deg)' },
          '50%': { transform: 'skew(3deg)' },
          '60%': { transform: 'skew(-1deg)' },
          '70%': { transform: 'skew(2deg)' },
          '80%': { transform: 'skew(-3deg)' },
          '90%': { transform: 'skew(1deg)' },
        },
        glitch: {
          '0%, 100%': { clip: 'rect(44px, 450px, 56px, 0)', transform: 'skew(0deg)' },
          '5%': { clip: 'rect(12px, 450px, 33px, 0)', transform: 'skew(5deg)' },
          '10%': { clip: 'rect(78px, 450px, 89px, 0)', transform: 'skew(-3deg)' },
          '15%': { clip: 'rect(23px, 450px, 45px, 0)', transform: 'skew(2deg)' },
          '20%': { clip: 'rect(67px, 450px, 78px, 0)', transform: 'skew(-4deg)' },
          '25%': { clip: 'rect(34px, 450px, 56px, 0)', transform: 'skew(3deg)' },
          '30%': { clip: 'rect(89px, 450px, 12px, 0)', transform: 'skew(-2deg)' },
          '35%': { clip: 'rect(45px, 450px, 67px, 0)', transform: 'skew(4deg)' },
          '40%': { clip: 'rect(23px, 450px, 34px, 0)', transform: 'skew(-5deg)' },
          '45%': { clip: 'rect(78px, 450px, 89px, 0)', transform: 'skew(2deg)' },
          '50%': { clip: 'rect(12px, 450px, 45px, 0)', transform: 'skew(-3deg)' },
          '55%': { clip: 'rect(67px, 450px, 78px, 0)', transform: 'skew(4deg)' },
          '60%': { clip: 'rect(34px, 450px, 56px, 0)', transform: 'skew(-2deg)' },
          '65%': { clip: 'rect(89px, 450px, 12px, 0)', transform: 'skew(3deg)' },
          '70%': { clip: 'rect(45px, 450px, 67px, 0)', transform: 'skew(-4deg)' },
          '75%': { clip: 'rect(23px, 450px, 34px, 0)', transform: 'skew(5deg)' },
          '80%': { clip: 'rect(78px, 450px, 89px, 0)', transform: 'skew(-2deg)' },
          '85%': { clip: 'rect(12px, 450px, 45px, 0)', transform: 'skew(3deg)' },
          '90%': { clip: 'rect(67px, 450px, 78px, 0)', transform: 'skew(-4deg)' },
          '95%': { clip: 'rect(34px, 450px, 56px, 0)', transform: 'skew(2deg)' },
        },
        blink: {
          '78%': { color: 'inherit', textShadow: 'inherit' },
          '79%': { color: '#242424' },
          '80%': { textShadow: 'none' },
          '81%': { color: 'inherit', textShadow: 'inherit' },
          '82%': { color: '#242424', textShadow: 'none' },
          '83%': { color: 'inherit', textShadow: 'inherit' },
          '92%': { color: '#242424', textShadow: 'none' },
          '92.5%': { color: 'inherit', textShadow: 'inherit' },
        },
        borderRadiusAnimation: {
          '0%': { borderRadius: '15px 80px 20px 70px' },
          '50%': { borderRadius: '80px 15px 70px 20px' },
          '100%': { borderRadius: '15px 80px 20px 70px' },
        },
        imageFloat: {
          '0%, 100%': { transform: 'translateY(0) rotate(0deg)' },
          '25%': { transform: 'translateY(-10px) rotate(2deg)' },
          '50%': { transform: 'translateY(0) rotate(0deg)' },
          '75%': { transform: 'translateY(10px) rotate(-2deg)' },
        },
        borderRotate: {
          '0%': { transform: 'rotate(0deg) scale(1)', borderColor: 'var(--neon-purple)' },
          '50%': { transform: 'rotate(180deg) scale(1.1)', borderColor: 'var(--primary-color)' },
          '100%': { transform: 'rotate(360deg) scale(1)', borderColor: 'var(--neon-blue)' },
        },
        borderPulse: {
          '0%, 100%': { transform: 'scale(1)', opacity: '0.5', borderColor: 'var(--primary-color)' },
          '50%': { transform: 'scale(1.1)', opacity: '1', borderColor: 'var(--neon-blue)' },
        },
        gridMove: {
          '0%': { transform: 'translate(0, 0)' },
          '100%': { transform: 'translate(50px, 50px)' },
        },
        borderGlow: {
          '0%': { opacity: '0.5', filter: 'hue-rotate(0deg)' },
          '50%': { opacity: '1', filter: 'hue-rotate(180deg)' },
          '100%': { opacity: '0.5', filter: 'hue-rotate(360deg)' },
        },
        sparkleFloat: {
          '0%, 100%': { transform: 'translate(0, 0) scale(1) rotate(0deg)', opacity: '0' },
          '25%': { transform: 'translate(3px, -3px) scale(1.2) rotate(30deg)', opacity: '0.8' },
          '50%': { transform: 'translate(0, 0) scale(1) rotate(0deg)', opacity: '0' },
          '75%': { transform: 'translate(-3px, 3px) scale(1.2) rotate(-30deg)', opacity: '0.8' },
        },
        techLineMove: {
          '0%, 100%': { transform: 'translateX(-100%)', opacity: '0', filter: 'brightness(1.2) blur(1px)' },
          '25%': { transform: 'translateX(-50%)', opacity: '0.8', filter: 'brightness(1.5) blur(1px)' },
          '50%': { transform: 'translateX(0)', opacity: '1', filter: 'brightness(1.8) blur(1px)' },
          '75%': { transform: 'translateX(50%)', opacity: '0.8', filter: 'brightness(1.5) blur(1px)' },
        },
        digitalPulse: {
          '0%, 100%': { opacity: '1' },
          '50%': { opacity: '0.8' },
        },
        glitchTop: {
          '0%': { transform: 'translate(-2px)', opacity: '0.8' },
          '20%': { transform: 'translate(2px)', opacity: '0.9' },
          '40%': { transform: 'translate(-1px)', opacity: '0.8' },
          '60%': { transform: 'translate(1px)', opacity: '0.9' },
          '80%': { transform: 'translate(-2px)', opacity: '0.8' },
          '100%': { transform: 'translate(2px)', opacity: '0.9' },
        },
        glitchBottom: {
          '0%': { transform: 'translate(2px)', opacity: '0.8' },
          '20%': { transform: 'translate(-2px)', opacity: '0.9' },
          '40%': { transform: 'translate(1px)', opacity: '0.8' },
          '60%': { transform: 'translate(-1px)', opacity: '0.9' },
          '80%': { transform: 'translate(2px)', opacity: '0.8' },
          '100%': { transform: 'translate(-2px)', opacity: '0.9' },
        },
        cornerPulse: {
          '0%, 100%': { transform: 'scale(1)', opacity: '0.8' },
          '50%': { transform: 'scale(1.1)', opacity: '1' },
        },
        'border-animate': {
          '0%': { borderColor: '#ff00c1', borderWidth: '4px', boxShadow: '0 0 0 0 #ff00c1', borderRadius: '10px' },
          '50%': { borderColor: '#ff3ad2', borderWidth: '4px', boxShadow: '0 0 0 10px rgba(255, 58, 210, 0.3)', borderRadius: '20px' },
          '100%': { borderColor: '#ff88e4', borderWidth: '4px', boxShadow: '0 0 0 0 #ff88e4', borderRadius: '10px' },
        },
        pulseContact: {
          '0%': { transform: 'scale(1)' },
          '100%': { transform: 'scale(1.2)' },
        },
        imageFade: {
          'from': { opacity: '0', transform: 'scale(1.2)' },
          'to': { opacity: '1', transform: 'scale(1)' },
        },
        infoFade: {
          'from': { opacity: '0', transform: 'translateX(50px)' },
          'to': { opacity: '1', transform: 'translateX(0)' },
        },
        pulseProject: {
          '0%': { transform: 'scale(1)' },
          '100%': { transform: 'scale(1.3)' },
        },
        bounceCute: {
          '0%, 100%': { transform: 'translateY(0) rotate(0deg)' },
          '50%': { transform: 'translateY(-10px) rotate(5deg)' },
        },
        wiggle: {
          '0%, 100%': { transform: 'rotate(0deg)' },
          '25%': { transform: 'rotate(5deg)' },
          '75%': { transform: 'rotate(-5deg)' },
        },
        floatCat: {
          '0%, 100%': { transform: 'translateY(0) rotate(0deg)' },
          '25%': { transform: 'translateY(-15px) rotate(3deg)' },
          '50%': { transform: 'translateY(0) rotate(0deg)' },
          '75%': { transform: 'translateY(-10px) rotate(-3deg)' },
        },
        heartBeat: {
          '0%, 100%': { transform: 'scale(1)' },
          '25%': { transform: 'scale(1.1)' },
          '50%': { transform: 'scale(1)' },
          '75%': { transform: 'scale(1.05)' },
        },
        sparkle: {
          '0%, 100%': { opacity: '0.3', transform: 'scale(0.8)' },
          '50%': { opacity: '1', transform: 'scale(1.2)' },
        },
      },
    },
  },
  plugins: [],
}

